from sqlalchemy import (
    Column, String, Text, DateTime, ForeignKey, Integer
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from src.database import Base
import uuid


class ChatSession(Base):
    __tablename__ = "chat_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Auto-generated from the first question (truncated to 100 chars)
    title = Column(String(100), nullable=False, default="New Chat")

    # Snapshot of the RAGConfig used — stored so the session can be replayed
    rag_config_json = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # Relationships
    messages = relationship(
        "ChatMessage",
        back_populates="session",
        cascade="all, delete-orphan",
        order_by="ChatMessage.created_at",
        lazy="dynamic",
    )
    user = relationship("User", lazy="select")

    def __repr__(self):
        return f"<ChatSession id={self.id} title={self.title!r}>"


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    session_id = Column(
        UUID(as_uuid=True),
        ForeignKey("chat_sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # 'user' | 'assistant'
    role = Column(String(20), nullable=False)

    # Plain text content:
    #   user    → the question as typed
    #   assistant → the answer generated by Gemini
    content = Column(Text, nullable=False)

    # JSON array of SourceChunk dicts — only populated for assistant messages
    sources_json = Column(Text, nullable=True)

    # JSON dict: {model_used, retrieval_strategy, chunks_retrieved}
    metadata_json = Column(Text, nullable=True)

    # Position in session for ordering (redundant with created_at but useful for fast sorts)
    turn_index = Column(Integer, nullable=False, default=0)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    # Relationships
    session = relationship("ChatSession", back_populates="messages")

    def __repr__(self):
        return f"<ChatMessage id={self.id} role={self.role} session={self.session_id}>"